
CREATE SCHEMA IF NOT EXISTS `back` DEFAULT CHARACTER SET utf8;
USE `back`;

CREATE TABLE IF NOT EXISTS `back`.`users` (
  `id` VARCHAR(255) NOT NULL,
  `fullName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;