name: back_shelf
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  collection: 1.18.0
  get_it: ^7.6.7
  dart_jsonwebtoken: ^2.13.0
  mysql1: ^0.20.0
  dartz: ^0.10.1
  password_dart: ^2.0.1


  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
